### ISSUE TITLE
piii para palavra (não apenas para letras)

### ISSUE THREAD

**Issue by felipenmoura** [lusofonia/piii.js#1]
Substituir a palavra toda, caso alguma flag seja passada.
Algo como:

``` js
piii("Vá se foder", "π", true); // "Vá se π"
piii("Vá se foder", "$#@%", true); // "Vá se $#@%"
```

O que acham?

**Comment by theuves** [comment]
Inicialmente, antes da versão 2.0.0, ele fazia isso utilizando `.replace()` ([veja como era](https://github.com/theuves/piii.js/blob/1.1.0/index.js)), porém percebi que estava havendo erros com a expressão regular ao filtrar palavras iniciadas ou terminadas com caracteres especiais (por exemplo, _cú_), pois na expressão regular é preciso usar `\b` para obter palavras inteiras, e isso parece [não funcionar com caracteres especiais](http://stackoverflow.com/questions/5436824/matching-accented-characters-with-javascript-regexes#5436944), por exemplo, `/\bcú\b/.test('cú')` retorna `false`.

Então a partir da versão 2.0.0 comecei a usar uma “gambiarrinha” para resolver esse problema, e que acaba deixando a censura com o mesmo comprimento do palavrão ([veja aqui](https://github.com/theuves/piii.js/blob/master/src/piii.js#L38-L52)).

Portanto, para substituir uma palavra inteira, teríamos que ter uma expressão que corresponda palavras iniciadas ou terminadas com caracteres especiais, ou encontrar outra maneira de resolver o problema sem o uso direto de expressões regulares.

**Comment by felipenmoura** [comment]
hm, entendi!
E se...sempre substituísse os caracteres da palavra que é um palavrão por um token, digamos: "_piii_".
E depois de aplicar as alterações como está sendo feito hoje, rodasse algo que substituísse apenas as repetições deste token, pelo que o usuário passou?

Algo tipo:

``` js
const TOKEN = "_piii_"
let result = piii("vá tomar no cú");
// result == "vá tomar no _piii__piii_"
```

Então, aplicando a substituição:

``` js
result.replace((new RegExp("("+TOKEN+")+", "g")), "π") // "vá tomar no π"
```

Acho que seguir um modelo de "tokenização" assim vai ser útil :)

**Comment by theuves** [comment]
Consegui resolvê-lo (com outra “gambiarrinha”, hehe). Não usei o modelo de _tokenização_ como você indicou, pois já estava planejando uma outra maneira de resolvê-lo antes de seu comentário. Resolvi-o “minerando” todas as partes não-palavrões da _string_ e adicionando-as em uma _array_ e em seguida juntando-a usando a _string_ de censura como um separador.

Ficou um pouco confuso, mas funciona bem.

**Comment by theuves** [comment]
:ship: `2.1.0` :tada:

> @felipenmoura Obrigado por tudo.
