### ISSUE TITLE
Adicionar verificações

### ISSUE THREAD

**Issue by philgruneich** [lusofonia/piii.js#2]
Gostaria de acrescentar outras palavras/expressões regulares na verificação do piii.js, existe algum método para "adicionar" novas expressões e estender o plugin?

**Comment by theuves** [comment]
<strike>Infelizmente ainda não há como fazer isso.

Recentemente eu estava pensando em formas de fazê-lo, mas ainda não cheguei a nenhuma resolução concreta ― para ser bem sincero ainda não há uma forma concreta nem de criar as expressões regulares dos palavrões padrões, pois expressões como "foder", que é um verbo, ficam muito grandes e de difícil leitura, recentemente, criei [uma ferramenta](/theuves/palavr) para tentar facilitar isso, mas não deu muito certo...</strike>

**Comment by theuves** [comment]
Agora você já pode criar seus próprios filtros.

:dancer::dancer: [Piii.js v4](https://github.com/piiijs/piii.js/tree/4.0.1) :tada:
