### ISSUE TITLE
Erro ao utilizar aliases com @

### ISSUE THREAD

**Issue by ricardoalvarenga101** [lusofonia/piii.js#7]
Ao tentar usar o alias a: ['@'] é retornado o regex:
\b(p+r+[o0]+s+t+[i1]+t+u+t+[a4@]+|m+[e3&]+r+d+[a4@]+|b+[o0]+c+[e3&]+t+[a4@]+|c+u+|p+[o0]+r+r+[a4@]+|f+[o0]+d+[e3&]+r+|c+[a4@]+r+[a4@]+l+h+[o0]+|p+u+t+[a4@]+)\b

que não valida a palavra digitada:
merd@

**Comment by theuves** [comment]
Vou analisar isso em breve.

Parece-me que está acontecendo somente com as palavras terminadas com caracteres que não são alphanuméricos (que se encaixe em `\w`).

...Pois `c@r@lho` funciona normalmente.

**Comment by ricardoalvarenga101** [comment]
alguma novidade quanto a correção?

**Comment by theuves** [comment]
Fechado. Veja #8 .
